# Generated by Django 3.2.8 on 2021-10-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='data',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='weather_info',
            field=models.JSONField(default=dict),
        ),
    ]
