# Generated by Django 3.2.8 on 2021-10-08 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20211008_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='created_by',
        ),
    ]
