# Generated by Django 3.2.8 on 2021-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_remove_weatherdata_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='weather_raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
